#GET
GET http://localhost:2001/api/v1/users


###
POST http://localhost:2001/api/v1/users
Content-Type: application/json

{
    "full_name": "John Doe",
    "dob": "1990-01-01",
    "gender": "Male",
    "mob_phone": "1234567890",
    "email": "johndoe@example.com",
    "email_ver": false,
    "passwd": "password123",
    "created_at": "2024-05-30T12:00:00Z"
}


###
POST http://localhost:2001/api/v1/users/login
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "passwd": "password123"
}